version: '3.9'

services:
  app:
    build: .
    container_name: nestjs-chatbot
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - USE_MOCK=false # Change to true if you will use a mock
    command: yarn start:dev